### ISSUE TITLE
Suggestion: Unclear message for signup password criteria

### ISSUE THREAD

**Issue by pannlnwza** [BioB3/ku-polls#46]
The registration form only displays an error message "Invalid username or password" when a password does not meet the required criteria (length, commonness). This makes it difficult for users to understand what is wrong with their password. You should display specific error messages that explain why the password is invalid, based on the password criteria ("Password must be at least 8 characters long," "Password is too common"), or provide criteria for valid usernames and passwords.

I think you can pass the `form` with errors to the template and call `form.errors` to get the error messages.

**Comment by BioB3** [comment]
Error messages showing the password criteria are added to the signup page.
